# Generated by Django 4.0.1 on 2022-10-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subscription_price',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
